### ISSUE TITLE
[TODO] Remove transpiling from node / browser testing

### ISSUE THREAD

**Issue by matthew-dean** [less/less-meta#41]
Tools like Vite can run just find without needing to "transpile" module code into CommonJS just for testing. Even browser builds could support module-based testing, as this would be supported by Chromium

### Blocked by
- [ ] https://github.com/less/less-meta/issues/42

### Sub-tasks
- [ ] Remove transpilation from builds
- [ ] Make sure tests are executing for all Node environments
- [ ] Make sure tests are executing for browser-based testing
